services:
  load-balancer:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - frontend
      - backend-python
      - backend-node
    networks:
      - resora-net
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - VITE_PYTHON_BACKEND_URL=
    depends_on:
      - backend-node
      - backend-python
    networks:
      - resora-net
    restart: always

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    networks:
      - resora-net
    restart: always

  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - WORKERS=2
    networks:
      - resora-net
    restart: always

networks:
  resora-net:
    driver: bridge
